Repository pagopa/pagopa-print-payment-notice-service, pull requests merged in 2024-08, with the labels that each got.

#53 Perf test
  .devops/performance-test-pipelines.yaml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_external.json
  performance-test/src/modules/notice_service_client.js
  performance-test/src/notice_massive_generation.js
  performance-test/src/test-types/ramp.json
  performance-test/src/test-types/stress.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/events/NoticeGenerationRequestProducerImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/async/AsyncService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/util/CommonUtility.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
Labels: minor, size/small

#55 [PPANTT-69] feat: introduced rewrite blob api proxy for notice
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_external.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/notices/service/storage/InstitutionsStorageClient.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClient.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notices/service/storage/InstitutionsStorageClientTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClientTest.java
Labels: minor, size/small

#48 [VAS-1099] feat: Add max number of notices as input for generate massive notices
  src/main/java/it/gov/pagopa/payment/notices/service/model/NoticeGenerationMassiveRequest.java
Labels: minor, size/small

#56 hotfix: rewrite
  openapi/openapi.json
  openapi/openapi_external.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/notices/service/storage/InstitutionsStorageClient.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClient.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/InstitutionsStorageClientTest.java
  src/test/resources/application.properties
Labels: size/large, patch

#57 hotfix: decoder
  src/main/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClient.java
Labels: bug, patch, size/small
