Repository pagopa/pagopa-print-payment-notice-service, pull requests merged in 2024-06, with the labels that each got.

#23 [VAS-1062] feat: add get ci data api
  .github/workflows/github_scripts/update_code.js
  .github/workflows/update_code.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/controller/InstitutionsController.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/institutions/UploadData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/CreditorInstitution.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Debtor.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/InstitutionsService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/InstitutionsServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/InstitutionsStorageClient.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notices/service/controller/InstitutionsControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/InstitutionsServiceImplTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/InstitutionsStorageClientTest.java
  src/test/resources/application.properties
Labels: enhancement, minor, size/large

#26 Next
  openapi/openapi.json
Labels: minor, size/small

#24 Bdd
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/features/generate.feature
  integration-test/src/features/single_generate.feature
  integration-test/src/features/single_generate_poste.feature
  integration-test/src/features/step_definitions/support/common.js
  integration-test/src/features/step_definitions/support/steps.js
  integration-test/src/package.json
  integration-test/src/resources/logo1.png
  integration-test/src/resources/scenario_ft_01.pdf
  integration-test/src/resources/scenario_ft_02.pdf
  integration-test/src/yarn.lock
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/controller/InstitutionsController.java
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/NoticeGenerationRequestItem.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/institutions/UploadData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/CreditorInstitution.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Debtor.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/InstallmentData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/NoticeRequestData.java
  src/main/resources/logback-spring.xml
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
Labels: size/large, patch

#30 Feat: update ci model
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/controller/InstitutionsController.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/institutions/UploadData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/CreditorInstitution.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/InstitutionsServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/InstitutionsStorageClient.java
Labels: enhancement, patch, size/small

#31 validator
  integration-test/src/features/2_installments.feature
  integration-test/src/features/single_generate.feature
  integration-test/src/features/single_generate_poste.feature
  integration-test/src/features/step_definitions/support/steps.js
  integration-test/src/resources/scenario_ft_05.pdf
  integration-test/src/resources/scenario_ft_06.pdf
  integration-test/src/resources/scenario_ft_09.pdf
  integration-test/src/resources/scenario_ft_10.pdf
  integration-test/src/yarn.lock
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/InstallmentData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Notice.java
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
Labels: size/large, patch

#33 fix: helm values
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#40 Fix helm
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: patch, size/small

#41 fix: apim policy
  openapi/openapi.json
  openapi/openapi_external.json
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeGenerationService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
Labels: patch, size/small

#43 [VAS-1145] fix: error model
  openapi/openapi.json
  openapi/openapi_external.json
  src/main/java/it/gov/pagopa/payment/notices/service/entity/PaymentNoticeGenerationRequestError.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/async/AsyncService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
Labels: bug, enhancement, size/large, patch

#46 Vas 1138 eseguire i perf test
  .devops/performance-test-pipelines.yaml
  .gitignore
  .identity/.terraform.lock.hcl
  performance-test/docker-compose.yaml
  performance-test/src/dev.environment.json
  performance-test/src/modules/notice_service_client.js
  performance-test/src/test-types/smoke.json
  performance-test/src/uat.environment.json
Labels: size/small, skip
