Repository pagopa/pagopa-print-payment-notice-service, pull requests merged in 2024-05, with the labels that each got.

#4 [VAS-825] feat: add get tables api
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticeTemplatesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/TemplateResource.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeTemplateService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/NoticeTemplateStorageClient.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notices/service/controller/NoticeTemplatesControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeTemplateServiceImplTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/NoticeTemplateStorageClientTest.java
  src/test/resources/application.properties
Labels: enhancement, minor

#7 Release
  .github/workflows/deploy_with_github_runner.yml
  .gitignore
  README.md
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
  infra/env/itn-dev/terraform.tfvars
  openapi/openapi.json
  pom.xml
  sops.sh
  src/main/resources/application-local.properties
  src/main/resources/application-local.properties.encrypted
  src/main/resources/application.properties
Labels: bug

#6 [VAS-827] feat: add single generation api
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/Application.java
  src/main/java/it/gov/pagopa/payment/notices/service/client/NoticeGenerationClient.java
  src/main/java/it/gov/pagopa/payment/notices/service/config/NoticeGenerationFeignConfig.java
  src/main/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestController.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/CreditorInstitution.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Debtor.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/InstallmentData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Installments.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeGenerationService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/NoticeTemplateStorageClient.java
  src/main/java/it/gov/pagopa/payment/notices/service/util/Constants.java
  src/main/java/it/gov/pagopa/payment/notices/service/util/WorkingDirectoryUtils.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
  src/test/resources/application.properties
Labels: minor, size/large

#8 rollback merge
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/Application.java
  src/main/java/it/gov/pagopa/payment/notices/service/client/NoticeGenerationClient.java
  src/main/java/it/gov/pagopa/payment/notices/service/config/NoticeGenerationFeignConfig.java
  src/main/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestController.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/CreditorInstitution.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Debtor.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/InstallmentData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Installments.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/AsyncService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeGenerationService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/NoticeTemplateStorageClient.java
  src/main/java/it/gov/pagopa/payment/notices/service/util/CommonUtility.java
  src/main/java/it/gov/pagopa/payment/notices/service/util/Constants.java
  src/main/java/it/gov/pagopa/payment/notices/service/util/WorkingDirectoryUtils.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/NoticeTemplateStorageClientTest.java
  src/test/resources/application.properties
Labels: bug, size/large, patch

#12 Fix generator call
  .github/workflows/create_dashboard.yaml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/notices/service/client/NoticeGenerationClient.java
  src/main/java/it/gov/pagopa/payment/notices/service/config/feign/NoticeFeignConfig.java
  src/main/resources/application-local.properties.encrypted
  src/main/resources/application.properties
Labels: size/small, skip

#9 [VAS-831] feat: add file recovery api
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/notices/service/config/NoticeGenerationFeignConfig.java
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/GetSignedUrlResource.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeGenerationService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClient.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notices/service/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/controller/NoticeTemplatesControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClientTest.java
  src/test/resources/application.properties
Labels: enhancement, minor, size/large

#10 [VAS-833] feat: add delete folder api
  .pre-commit-config.yaml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeGenerationService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClient.java
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClientTest.java
Labels: enhancement, minor, size/small

#11 Vas 830 feat add get folder api
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeGenerationService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
Labels: enhancement, minor, size/small

#14 int test
  .github/workflows/cd_main.yml
  .github/workflows/cd_next.yml
  .github/workflows/check_pr.yml
  .github/workflows/ci_anchore.yml
  .github/workflows/ci_code_review.yml
  .github/workflows/ci_integration_test.yml
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/github_scripts/check_required_labels.js
  .github/workflows/github_scripts/check_size.js
  .github/workflows/github_scripts/check_source_branch.js
  .github/workflows/github_scripts/make_latest_release.js
  .github/workflows/release_deploy.yml
  .identity/00_data.tf
  .identity/01_github_environment.tf
  .pre-commit-config.yaml
  docker/docker-compose.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/features/example.feature
  integration-test/src/features/generate.feature
  integration-test/src/features/step_definitions/support/common.js
  integration-test/src/features/step_definitions/support/steps.js
  integration-test/src/package.json
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/notices/service/config/NoticeGenerationFeignConfig.java
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/GetSignedUrlResource.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeGenerationService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClient.java
  src/main/resources/application-local.properties.encrypted
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notices/service/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/controller/NoticeTemplatesControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClientTest.java
  src/test/resources/application.properties
Labels: size/large, skip

#15 [VAS-832] feat: add upload ci data api
  .github/workflows/check_pr.yml
  .github/workflows/ci_code_review.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/controller/InstitutionsController.java
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticeTemplatesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/enums/PaymentGenerationRequestStatus.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/institutions/UploadData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/CreditorInstitution.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/InstallmentData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/InstitutionsService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeGenerationService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/InstitutionsServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/storage/InstitutionsStorageClient.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notices/service/controller/InstitutionsControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/InstitutionsServiceImplTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/InstitutionsStorageClientTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/storage/NoticeStorageClientTest.java
  src/test/resources/application.properties
Labels: enhancement, minor, size/large

#17 Swagger
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notices/service/controller/InstitutionsController.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/InstallmentData.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/async/AsyncService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/InstitutionsServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
Labels: size/small, skip
