Repository pagopa/pagopa-print-payment-notice-service, pull requests merged in 2024-07, with the labels that each got.

#47 [VAS-1114] feat: add idempotency check
  integration-test/src/yarn.lock
  openapi/openapi.json
  openapi/openapi_external.json
  src/main/java/it/gov/pagopa/payment/notices/service/config/OpenApiConfig.java
  src/main/java/it/gov/pagopa/payment/notices/service/controller/NoticesController.java
  src/main/java/it/gov/pagopa/payment/notices/service/entity/PaymentNoticeGenerationRequest.java
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/InstallmentData.java
  src/main/java/it/gov/pagopa/payment/notices/service/repository/PaymentGenerationRequestRepository.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/NoticeGenerationService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/util/Constants.java
  src/test/java/it/gov/pagopa/payment/notices/service/controller/GenerationRequestControllerTest.java
  src/test/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImplTest.java
Labels: enhancement, minor, size/large

#49 fix: duedate not required
  openapi/openapi.json
  openapi/openapi_external.json
  src/main/java/it/gov/pagopa/payment/notices/service/model/notice/InstallmentData.java
Labels: bug, size/large, patch

#50 logging + small changes
  integration-test/src/features/massive_generate.feature
  integration-test/src/features/single_generate.feature
  integration-test/src/features/step_definitions/support/common.js
  integration-test/src/features/step_definitions/support/steps.js
  integration-test/src/resources/scenario_ft_21.pdf
  src/main/java/it/gov/pagopa/payment/notices/service/service/async/AsyncService.java
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notices/service/util/CommonUtility.java
Labels: size/large, patch

#51 Hotfix idempotency
  src/main/java/it/gov/pagopa/payment/notices/service/service/impl/NoticeGenerationServiceImpl.java
Labels: bug, patch, size/small

#52 fix: updated openapi to remove unused parameters
  openapi/openapi.json
  openapi/openapi_external.json
Labels: size/large, skip
